version: 1
machine:
  environment:
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run: 
          name: Build gradle
          command: cd AndroidDemo/;./gradlew androidDependencies
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
      - run:
         name: Launch emulator
         command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
         background: true
      - run:
          name: Wait emulator
          command: |
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run EspressoTest
          command: cd AndroidDemo/;./gradlew app:connectedAndroidTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
        
          

